# Entities blacklisted from using portals
# Possible values listed here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/entity/EntityType.html

Blacklisted-Portal-Entities:
  - "DROPPED_ITEM"
  - "BOAT"
  - "CHEST_BOAT"
  - "MINECART"
  - "MINECART_CHEST"
  - "MINECART_COMMAND"
  - "MINECART_FURNACE"
  - "MINECART_TNT"
  - "MINECART_HOPPER"
  - "MINECART_MOB_SPAWNER"