name: PortalGuard
version: 1.0.3
author: MetallicGoat
main: me.metallicgoat.portalguard.PortalGuard
description: Prevents certain types of entities from going through nether portals
api-version: 1.13
